fail_on_violations: true
javascript:
  enabled: false
eslint:
  enabled: true
  config_file: .eslintrc
  ignore_file: .eslintignore
css:
  enabled: false
# Stylelint support is coming:
# https://github.com/platanus/hound/pull/8
#
# stylelint:
#   enabled: true
#   config_file: .stylelintrc
#   ignore_file: .stylelintignore
