fail_on_violations: true
javascript:
  enabled: false
eslint:
  enabled: true
  config_file: .eslintrc
  ignore_file: .eslintignore
css:
  enabled: false
stylelint:
  enabled: true
  config_file: .stylelintrc
  ignore_file: .stylelintignore
